version: '3.7'

services:
  portainer:
    image: portainer/portainer
    restart: always
    container_name: portainer-aula-lbd
    ports: 
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/renatogroffe/Desenvolvimento/Portainer/data:/data
    networks: 
      lbd_aula:
        ipv4_address: 172.10.0.3

  db:
    image: mysql:latest
    container_name: "mysql"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    environment:
      #senha do mysql
      - MYSQL_ROOT_PASSWORD=123
    networks: 
      lbd_aula:
        ipv4_address: 172.10.0.4

networks: 
  lbd_aula:
    driver: bridge
    ipam: 
      driver: default
      config: 
        - subnet: 172.10.0.0/24  
